# Generated by Django 4.0.6 on 2022-07-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_checkedcart_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
